### ISSUE TITLE
Problem with query

### ISSUE THREAD

**Issue by ricardopxlcl** [superinsight/superinsight-db#135]
When i execute the example query:

`SELECT mldb.movie._id, mldb.movie.title, mldb.movie.overview, predictions.score
FROM mldb.movie
JOIN model.semantic_search
ON model.semantic_search.inputs = mldb.movie.overview
WHERE mldb.movie._id < 20
AND model.semantic_search.similar = 'gangster'
ORDER BY predictions.score DESC
`

Have this response:
`SQL Error [42P01]: ERROR: missing FROM-clause entry for table "predictions"`

Screenshot response:
https://prnt.sc/rlKDo-CGVWIP

¿Can you help me?

**Comment by csnelsonchu** [comment]
We just tested out the latest build.
It seems to be working fine. I am guessing there is some issues with the SQL Editor plugin I am seeing on the screenshot.
Can you tried using [DBeaver](https://dbeaver.io/) to connect and see if you can run it?

**Comment by ricardopxlcl** [comment]
> We just tested out the latest build. It seems to be working fine. I am guessing there is some issues with the SQL Editor plugin I am seeing on the screenshot. Can you tried using [DBeaver](https://dbeaver.io/) to connect and see if you can run it?

Thanks for u reply. Im re-install with Debian now (Previous installed Centos) and now have this message error:

Query without Join (Work)
https://prnt.sc/2icbUzX2WyIb

Query with Join (Not work)
https://prnt.sc/aZy7_7BMgD4W

Response error:
`SQL Error [42P01]: ERROR: relation "model._predict_00e283202c0a47ec899337041adae28c" does not exist
  Position: 105

Error position: line: 3 pos: 104`


I only follow this steps:
http://docs.superinsight.ai/quickstart/

Regards,

**Comment by csnelsonchu** [comment]
Hi @ricardopxlcl 
You mentioned you are using Debian instead of Centos, are you using the docker install option?
Can you upload the logs on the install?
I suspect there are some issues during the docker run process.

**Comment by ricardopxlcl** [comment]
Hi ! Yes im using the docker install option. In my first comment y try to use Centos, and today Install a new Machine with Debian 11 to try. This is the log https://pastebin.com/r5Ca2W5e

**Comment by csnelsonchu** [comment]
@ricardopxlcl
Can you delete your docker image and docker volume and try again?
I see a problem right around 2023-03-08 07:33:43.181 UTC [1] LOG
Looks like there are some issues left from the previous docker volume

**Comment by csnelsonchu** [comment]
@ricardopxlcl 
Awesome troubleshooting !
Thanks for sharing how you resolve this issue, awesome logs and recording by the way.
I'll close this ticket now, thanks!
